### ISSUE TITLE
Bcrypt load error on Windows

### ISSUE THREAD

**Issue by J-F-Liu** [J-F-Liu/CompanyConsole#1]
~~~~~~~~~~~~~~~~~~~~~~~~
C:/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10-x86-mingw32/lib/bcrypt.rb:17:in `require': 126: The specified module could not be found. 
  - C:/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10-x86-mingw32/lib/2.1/bcrypt_ext.so (LoadError)
from C:/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10-x86-mingw32/lib/bcrypt.rb:17:in `rescue in <top (required)>'
~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by J-F-Liu** [comment]
Solution:
Run `gem install bcrypt --platform=ruby`
Then copy `C:\ruby-2.2.1\lib\ruby\gems\2.2.0\gems\bcrypt-3.1.10\lib\bcrypt_ext.so` to `C:\ruby-2.2.1\lib\ruby\gems\2.2.0\gems\bcrypt-3.1.10-x86-mingw32\lib`
